### ISSUE TITLE
Configure Mailgun SMTP

### ISSUE THREAD

**Issue by osterman** [cloudposse/slackin#3]
## what
* Add support for SMTP

## why
* So we can track deliverability and reduce spam rate

**Comment by alebabai** [comment]
@osterman Could you clarify what do you mean?
Slackin uses Slack REST API to send invites - there isn't any SMTP client, just post to `https://${org}.slack.com/api/users.admin.invite` url - and then slack server sends invite email.

**Comment by osterman** [comment]
Never mind. Slack sends the emails =)
